export const dataPortfolio = [
  {
    id: 0,
    title: "Personal Trainer",
    imgUrl: "/img-projects/personaltrainer.jpg",
    slug: "personal-trainer",
    type: " Proyecto a medida",
    imgs: [
      { id: 0, imgUrl: "/img-projects/personal/p-img-1.png" },
      { id: 1, imgUrl: "/img-projects/personal/p-img-2.png" },
      { id: 2, imgUrl: "/img-projects/personal/p-img-3.png" },
      { id: 3, imgUrl: "/img-projects/personal/p-img-4.png" },
      { id: 4, imgUrl: "/img-projects/personal/p-img-5.png" },
      { id: 5, imgUrl: "/img-projects/personal/p-img-6.png" },
      { id: 6, imgUrl: "/img-projects/personal/p-img-7.png" },
      { id: 7, imgUrl: "/img-projects/personal/p-img-8.png" },
    ],
    urlWebSite: "https://pablosalinacoach.netlify.app/",
  },
  {
    id: 1,
    title: "Diario El Heraldo | de Concordia",
    imgUrl: "/img-projects/logo-heraldo.jpg",
    slug: "el-heraldo",
    type: " Proyecto a medida",
    imgs: [
      { id: 0, imgUrl: "/img-projects/diary/d-img-1.png" },
      { id: 1, imgUrl: "/img-projects/diary/d-img-2.png" },
      { id: 2, imgUrl: "/img-projects/diary/d-img-3.png" },
      { id: 3, imgUrl: "/img-projects/diary/d-img-4.png" },
      { id: 4, imgUrl: "/img-projects/diary/d-img-5.png" },
    ],
    urlWebSite: "https://www.elheraldo.com.ar/",
  },
  {
    id: 2,
    title: "Ángeles Callejeros",
    imgUrl: "/img-projects/logo-angeles.svg",
    slug: "angeles-callejeros",
    type: " Proyecto a medida",
    imgs: [
      { id: 0, imgUrl: "/img-projects/ONG/o-img-1.png" },
      { id: 1, imgUrl: "/img-projects/ONG/o-img-2.png" },
      { id: 2, imgUrl: "/img-projects/ONG/o-img-3.png" },
      { id: 3, imgUrl: "/img-projects/ONG/o-img-4.png" },
      { id: 4, imgUrl: "/img-projects/ONG/o-img-5.png" },
      { id: 4, imgUrl: "/img-projects/ONG/o-img-6.png" },
      { id: 4, imgUrl: "/img-projects/ONG/o-img-7.png" },
    ],
    urlWebSite: "https://www.angelescallejeros.org.ar/",
  },
];
