export const imagesSkills = [
  { id: 0, title: "HTML5", imageUrl: "/imgs-skills/html.svg" },
  { id: 1, title: "CSS3", imageUrl: "/imgs-skills/css.svg" },
  { id: 2, title: "JavaScript", imageUrl: "/imgs-skills/js.svg" },
  { id: 3, title: "TypeScript", imageUrl: "/imgs-skills/ts.svg" },
  { id: 4, title: "ReactJS", imageUrl: "/imgs-skills/react.svg" },
  { id: 5, title: "Angular", imageUrl: "/imgs-skills/angular.svg" },
  { id: 6, title: "NextJS", imageUrl: "/imgs-skills/nextjs.svg" },
  { id: 7, title: "TailwindCSS", imageUrl: "/imgs-skills/tailwindcss.svg" },
  { id: 8, title: "MaterialUI", imageUrl: "/imgs-skills/materialui.svg" },
  { id: 9, title: "Redux", imageUrl: "/imgs-skills/redux.svg" },
  { id: 10, title: "NodeJS", imageUrl: "/imgs-skills/nodejs.svg" },
  { id: 11, title: "Python", imageUrl: "/imgs-skills/python.svg" },
  { id: 12, title: "MongoDB", imageUrl: "/imgs-skills/mongodb.svg" },
  { id: 13, title: "PostgreSQL", imageUrl: "/imgs-skills/postgre.svg" },
  { id: 14, title: "git", imageUrl: "/imgs-skills/git.svg" },
];
