export const imagesSkills = [
  { id: 0, title: "HTML5", imageUrl: "/skills/html.svg" },
  { id: 1, title: "CSS3", imageUrl: "/skills/css.svg" },
  { id: 2, title: "JavaScript", imageUrl: "/skills/js.svg" },
  { id: 3, title: "TypeScript", imageUrl: "skills/ts.svg" },
  { id: 4, title: "ReactJS", imageUrl: "skills/react.svg" },
  { id: 5, title: "Angular", imageUrl: "skills/angular.svg" },
  { id: 6, title: "NextJS", imageUrl: "skills/nextjs.svg" },
  { id: 7, title: "TailwindCSS", imageUrl: "skills/tailwindcss.svg" },
  { id: 8, title: "MaterialUI", imageUrl: "skills/materialui.svg" },
  { id: 9, title: "Redux", imageUrl: "skills/redux.svg" },
  { id: 10, title: "NodeJS", imageUrl: "skills/nodejs.svg" },
  { id: 11, title: "Python", imageUrl: "skills/python.svg" },
  // { id: 12, title: "Java", imageUrl: "skills/java.svg" },
  { id: 13, title: "MongoDB", imageUrl: "skills/mongodb.svg" },
  { id: 14, title: "PostgreSQL", imageUrl: "skills/postgre.svg" },
  { id: 15, title: "git", imageUrl: "skills/git.svg" },
];
